- label: C贸mo empezar
  items:
    - name: Instalaci贸n
      link: /docs/como-empezar/instalacion
    - name: Configuraci贸n
      link: /docs/como-empezar/configuracion

- label: M贸dulos
  items:
    - name: Recetario
      link: /docs/modulos/recetario
    - name: Remanentes
      link: /docs/modulos/sobras
    - name: Informes
      link: /docs/modulos/informes